PROGRAM Response(INPUT, OUTPUT);
USES
  GPC; 
BEGIN
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('REQUEST_METHOD');
  WRITELN;
  WRITELN('QUERY_STRING');
  WRITELN;
  WRITELN('CONTENT_LENGTH');
  WRITELN; 
  WRITELN('HTTP_USER_AGENT');
  WRITELN;
  WRITELN('HTTP_HOST');
  WRITELN;
END.
